fix task 0 (v2)

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,8 +1,15 @@
 #!/bin/bash
+# Write a Bash script that transfers 
+# a file from our client to a server
 
 if [ "$#" -ne 4 ]; then
   echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
 else
-  scp -i "$4" "$1" "$3@$2:~/"
+  if [ ! -f "$1" ]; then
+    echo "'$1' file not found."
+    exit 1
+  fi
+
+  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
 fi
 
