Update (whoami?)

diff --git a/0x12-web_stack_debugging_2/0-iamsomeoneelse b/0x12-web_stack_debugging_2/0-iamsomeoneelse
--- a/0x12-web_stack_debugging_2/0-iamsomeoneelse
+++ b/0x12-web_stack_debugging_2/0-iamsomeoneelse
@@ -1,3 +1,14 @@
 #!/usr/bin/env bash
-# run commend for a specific user
-sudo -u "$1" whoami
+# Run a command for a specific user
+
+if [ "$#" -eq 0 ]; then
+  echo "Usage: $0 <username>"
+  exit 1
+fi
+
+if sudo -u "$1" true 2>/dev/null; then
+  sudo -u "$1" whoami
+else
+  echo "user $1 not found."
+fi
+
